name: Golang Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: version
        run: |
          if [ -f go.mod ]; then
            version=$(grep '^go [0-9]' go.mod | awk '{print $2}')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          else
            echo "Erreur : le fichier go.mod est introuvable."
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: version
    strategy:
      matrix:
        goos: [linux, windows, macos]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.version.outputs.version }}

      - name: Build
        env:
          MATRIX_GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          if [ "$MATRIX_GOOS" == "macos" ]; then
            export GOOS="darwin"
          else
            export GOOS="$MATRIX_GOOS"
          fi
          mkdir -p output
          output_name="NodeMonitor-${MATRIX_GOOS}-$GOARCH"
          if [ "$MATRIX_GOOS" == "windows" ]; then
            output_name="$output_name.exe"
          fi
          go build -o "output/$output_name" ./...

      - name: Set asset file and name
        id: set_output_file
        env:
          MATRIX_GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          if [ "$MATRIX_GOOS" == "macos" ]; then
            file="./output/NodeMonitor-macos-$GOARCH"
            name="NodeMonitor-macos-$GOARCH"
          else
            file="./output/NodeMonitor-$MATRIX_GOOS-$GOARCH"
            name="NodeMonitor-$MATRIX_GOOS-$GOARCH"
          fi
          if [ "$MATRIX_GOOS" == "windows" ]; then
            file="$file.exe"
            name="$name.exe"
          fi
          if [ -f "$file" ]; then
            echo "file=$file" >> "$GITHUB_OUTPUT"
            echo "name=$name" >> "$GITHUB_OUTPUT"
          else
            echo "Erreur : le fichier $file n'existe pas."
            exit 1
          fi

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.set_output_file.outputs.file }}
          asset_name: ${{ steps.set_output_file.outputs.name }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
